### ISSUE TITLE
Import data from JSON

### ISSUE THREAD

**Issue by tommardh** [paddelkraft/TfsKanbanBuddy#4]
AS a developer
I WANT TO be able to import data from a JSON file exported
IN ORDER TO have the data collected by another client available in mine 

GIVEN there exists snapshot data in the tool
AND a valid JSON export file
WHEN I import the JSON file
THEN the snapshot data in the tool should be replaced by the data in the JSON file

**Comment by paddelkraft** [comment]
available in a dev page
